---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demo
  namespace: demo-project
  labels:
    app: springboot-demo
  annotations:
    backstage.io/kubernetes-id: springboot-demo
    backstage.io/kubernetes-namespace: demo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-demo
  template:
    metadata:
      labels:
        app: springboot-demo
    spec:
      containers:
        - name: springboot
          image: image-registry.openshift-image-registry.svc:5000/demo-project/springboot-demo-backend:latest
          ports:
            - containerPort: 7890
        - name: react-app
          image: image-registry.openshift-image-registry.svc:5000/demo-project/springboot-demo-frontend:latest
          ports:
            - containerPort: 3000
