---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: demo-project
spec:
  selector:
    app: springboot-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7890
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: demo-project
spec:
  selector:
    app: springboot-demo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
